// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN25_aiP8PhBEVqN-H-CBfr390n9Nsld0',
    appId: '1:163714609978:web:3001c61425539e3d7b1603',
    messagingSenderId: '163714609978',
    projectId: 'pedometer-gamification',
    authDomain: 'pedometer-gamification.firebaseapp.com',
    storageBucket: 'pedometer-gamification.appspot.com',
    measurementId: 'G-V2N4K176W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyyUxgxLCjcYpC5Tn2J_LrVnRibKeBM0',
    appId: '1:163714609978:android:d2b1459a596469817b1603',
    messagingSenderId: '163714609978',
    projectId: 'pedometer-gamification',
    storageBucket: 'pedometer-gamification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrtDBPcr76GwwKdrbY6B5Bm5JHheQC5w',
    appId: '1:163714609978:ios:758310dda2a79d3a7b1603',
    messagingSenderId: '163714609978',
    projectId: 'pedometer-gamification',
    storageBucket: 'pedometer-gamification.appspot.com',
    iosClientId:
        '163714609978-df2ss6fpeoa5r0a4vfq029df2nl747k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.step',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDrtDBPcr76GwwKdrbY6B5Bm5JHheQC5w',
    appId: '1:163714609978:ios:758310dda2a79d3a7b1603',
    messagingSenderId: '163714609978',
    projectId: 'pedometer-gamification',
    storageBucket: 'pedometer-gamification.appspot.com',
    iosClientId:
        '163714609978-df2ss6fpeoa5r0a4vfq029df2nl747k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.step',
  );
}
